### PR TITLE
CDL @unibuc

### PR DESCRIPTION
**Pull request by maria**
Update the site info for the CDL @ unibuc edition.
# Work in progress

### CODE REVIEW

**Comment by ghost** [comment]
I have a minor suggestion.
It may be a better idea to make these changes in a separate branch (maybe call it "unibuc").
The only thing that would otherwise need to change in that case is the "git pull" command in the autodeploy Makefile.

**Comment by maria** [comment]
> It may be a better idea to make these changes in a separate branch (maybe call it "unibuc").

Do you mean: `rosedu:unibuc` ?

**Comment by ghost** [comment]
No, not a new repository under ROSEdu's account. I meant a separate branch under the cdl.rosedu.org repository.
Let "master" remain exclusively the ACS-UPB edition, and create "unibuc" to be the FMI edition.

**Comment by maria** [comment]
I meant `cdl.rosedu.org:unibuc`, sorry.

**Comment by ghost** [comment]
Yes, exactly.

**Pull request closed without merging**
